export {
  DEMO_COMPANY,
  DEMO_USERS,
  DEMO_PROJECTS,
  ALL_PROJECT_MEMBERS,
  DEMO_MILESTONES,
  DEMO_TASKS,
  DEMO_DAILY_REPORTS,
  DEMO_RISKS,
  DEMO_ACTIVITIES,
  DEMO_NOTIFICATIONS,
  ALL_DEMO_DATA,
} from "./data";
export type { Milestone } from "./data";
export type { ActivityLog } from "./data";
export type { DemoNotification } from "./data";

export {
  calculateProjectHealth,
  formatCurrency,
  formatNumber,
  applySearchFilter,
  applyRangeFilter,
  createId,
  nowISO,
  filterProjects,
  toProjectSummary,
  listDemoProjects,
  getDemoProject,
  createDemoProject,
  updateDemoProject,
  deleteDemoProject,
  getDemoDashboardStats,
  filterTasks,
  listDemoTasks,
  getDemoTask,
  createDemoTask,
  updateDemoTask,
  deleteDemoTask,
  listDemoReports,
  getDemoReport,
  createDemoReport,
  updateDemoReportStatus,
  updateDemoReport,
  filterRisks,
  listDemoRisks,
  getDemoRisk,
  createDemoRisk,
  updateDemoRisk,
  closeDemoRisk,
  resetDemoProjects,
  resetDemoTasks,
  resetDemoRisks,
  resetDemoDailyReports,
} from "./repositories";

export {
  simulateProgressUpdate,
  simulateCostOverrun,
  delayProject,
  completeProject,
  resetAllDemoData,
  generateDelayScenario,
  generateBudgetScenario,
} from "./scenarios";
