export const demoConfig = {
  enabled: process.env.NEXT_PUBLIC_DEMO_MODE === "true",
  demoUser: {
    id: "demo-user-001",
    email: "demo@jaadbuild.com",
    nameAr: "مدير النظام التجريبي",
    nameEn: "Demo System Admin",
    locale: "ar",
    role: "TENANT_OWNER",
  },
  demoSwitchRoles: [
    { id: "TENANT_OWNER", nameAr: "مالك الشركة", nameEn: "Tenant Owner" },
    { id: "EXECUTIVE_MANAGER", nameAr: "المدير التنفيذي", nameEn: "Executive Manager" },
    { id: "PROJECTS_DIRECTOR", nameAr: "مدير المشاريع", nameEn: "Projects Director" },
    { id: "PROJECT_MANAGER", nameAr: "مدير مشروع", nameEn: "Project Manager" },
    { id: "SITE_ENGINEER", nameAr: "مهندس موقع", nameEn: "Site Engineer" },
    { id: "PLANNING_ENGINEER", nameAr: "مهندس تخطيط", nameEn: "Planning Engineer" },
    { id: "HSE_OFFICER", nameAr: "مسؤول سلامة", nameEn: "HSE Officer" },
    { id: "VIEWER", nameAr: "مشاهد", nameEn: "Viewer" },
  ],
  permissionsByRole: {
    TENANT_OWNER: ["dashboard.view", "projects.view", "projects.create", "projects.update", "projects.delete", "users.view", "users.invite", "users.manage_roles", "settings.view", "settings.update", "billing.view", "reports.view"],
    EXECUTIVE_MANAGER: ["dashboard.view", "projects.view", "projects.create", "projects.update", "reports.view", "settings.view"],
    PROJECTS_DIRECTOR: ["dashboard.view", "projects.view", "projects.create", "projects.update", "reports.view"],
    PROJECT_MANAGER: ["dashboard.view", "projects.view", "projects.update", "tasks.view", "tasks.create", "tasks.update", "reports.view", "daily_reports.view", "daily_reports.create", "daily_reports.approve", "risks.view", "risks.create", "risks.update"],
    SITE_ENGINEER: ["dashboard.view", "projects.view", "tasks.view", "tasks.update", "daily_reports.view", "daily_reports.create", "daily_reports.submit", "risks.view", "risks.create"],
    PLANNING_ENGINEER: ["projects.view", "milestones.view", "milestones.update", "reports.view"],
    HSE_OFFICER: ["projects.view", "daily_reports.view", "risks.view", "risks.create"],
    VIEWER: ["dashboard.view", "projects.view"],
  },
  permissionsList: [
    { key: "dashboard.view", nameAr: "عرض لوحة التحكم", module: "dashboard" },
    { key: "projects.view", nameAr: "عرض المشاريع", module: "projects" },
    { key: "projects.create", nameAr: "إنشاء مشروع", module: "projects" },
    { key: "projects.update", nameAr: "تعديل مشروع", module: "projects" },
    { key: "projects.delete", nameAr: "حذف مشروع", module: "projects" },
    { key: "tasks.view", nameAr: "عرض المهام", module: "tasks" },
    { key: "tasks.create", nameAr: "إنشاء مهمة", module: "tasks" },
    { key: "tasks.update", nameAr: "تعديل مهمة", module: "tasks" },
    { key: "milestones.view", nameAr: "عرض المراحل", module: "milestones" },
    { key: "milestones.update", nameAr: "تحديث المراحل", module: "milestones" },
    { key: "daily_reports.view", nameAr: "عرض التقارير", module: "daily_reports" },
    { key: "daily_reports.create", nameAr: "إنشاء تقرير", module: "daily_reports" },
    { key: "daily_reports.submit", nameAr: "تقديم تقرير", module: "daily_reports" },
    { key: "daily_reports.approve", nameAr: "اعتماد تقرير", module: "daily_reports" },
    { key: "risks.view", nameAr: "عرض المخاطر", module: "risks" },
    { key: "risks.create", nameAr: "إنشاء مخاطرة", module: "risks" },
    { key: "risks.update", nameAr: "تعديل مخاطرة", module: "risks" },
    { key: "team.view", nameAr: "عرض الفريق", module: "team" },
    { key: "users.view", nameAr: "عرض المستخدمين", module: "users" },
    { key: "users.invite", nameAr: "دعوة مستخدم", module: "users" },
    { key: "settings.view", nameAr: "عرض الإعدادات", module: "settings" },
    { key: "settings.update", nameAr: "تعديل الإعدادات", module: "settings" },
    { key: "reports.view", nameAr: "عرض التقارير", module: "reports" },
    { key: "billing.view", nameAr: "عرض الفواتير", module: "billing" },
  ],
  tenantNameAr: "شركة الأفق المتقدمة للمقاولات",
  tenantNameEn: "Advanced Horizon Contracting Co.",
  demoNotice: "هذه نسخة تجريبية من النظام. البيانات المعروضة هي بيانات عرض توضيحي.",
};
